[package]
name = "testavimas_tictactoe"
version = "0.1.0"
authors = ["Emilis MargeviÄius <s034932@ad.viko.lt>"]
edition = "2018"



[dependencies]
# GUI
iced = "0.3.0"
# JSON
serde_json = "1.0"
# fltk = { version = "^1.2", features = ["fltk-bundled"] }
